# Generated by Django 2.2.5 on 2019-10-21 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSpagemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=200)),
                ('meta_keyword', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=200)),
                ('cmsfile', models.FileField(upload_to='cmspage/')),
                ('html_description', models.TextField(max_length=65500)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
