# Generated by Django 2.2.5 on 2019-11-13 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0002_addgeneralsettingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SMTP_EMAIL', models.EmailField(default='wwwsmtp@24livehost.com', max_length=200)),
                ('SMTPPASSWORD', models.TextField(default='HhOwXOnOB#Oi(amb2NBTD>ZsVcVTpQO+{}rP)~JBI4^8aZ!vmzHfnQ5axqRxcx6_2M`vkFbVEuvRy9RPad}lZcvMs?VJk6jOIJ@=Sw~k_GD~M`S$1b_OHoxTNNG}JM_5NQFjR12D^O2wc2!GBGj~sUN_Ip{F;8JtIae@iYe;TpN=tT3D=RflcTq)EVMjr9Mrtu-Vp4f|IcGFwHAGV~PcS)1VoX#wFfna#Fi19HFm7XTaw}PSdSo?vH+EDvWNdg%W@KepFm-8qa#}-XFj87CZC6J#bWLzgaY;FKQ$;avGDb;7b5Cz$H&81%Fe@)HV{utbK~70RMP@l{Z#G0Sa%3}BQF${&GHNwwQZa32D@!kNMruVvHZw6<Yi%|(W@R!?R53DbFjHl5ML1DNXG>LAOnOaZSu$*4NMUa{bU9OQc1A~0LOCl*Yj8zESa^9wa%@FKd1P=%ZEH9yVPs2Eb1`j5NmF)VRYgN;NlG$vVlrcQFF8qYG-FpWMQ>$Ac4|mkOi3~~XK-tIZ)8JLNLF!GWJGvYPDyb#OifB^YBNZ3MM!EZRd;7iZ&71eNKQ{?bT~0DN^e?8cTZVRcuZPHIA%dhcyvX0O?PopX?izLc5O{fRC!ZXN@j9OM?r6HWm-ouZ#ZR0buUDEF>Z20RccKuY&cbFFjaXrW-(}XT3AhZK{r=9Gifnucui(VV`?@^YI03!c6w)eRdr!hXiQE~cuYlUR$4K2RCjVga5!>KYg$TpO?FjzdS^2?FIZ<-Z+baPHe)q5Z#QOVS5ZVbGfieQYfn~YLTF`Wc2H|DcsX-QX;yPnbYysFZevAJO>{XybzxaoIYKi^Giho$ctvMXSyEy#QDs(nNN#RnPIp;7', max_length=2000)),
                ('SMTPPORT', models.IntegerField(default=465)),
                ('SMTPUSERNAME', models.CharField(default='mail.24livehost.com', max_length=100)),
                ('SMTP_ALLOW', models.BooleanField(default=True)),
                ('SMTPTLS', models.BooleanField(default=False)),
                ('setting_checkbox', models.BooleanField(default=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
