# Generated by Django 2.2.5 on 2019-11-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_smtpdetailmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smtpdetailmodel',
            name='setting_checkbox',
        ),
    ]
