# Generated by Django 2.2.5 on 2019-11-14 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0004_remove_smtpdetailmodel_setting_checkbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialURLsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('social_value', models.CharField(default='0_socialvalue', max_length=200, unique=True)),
                ('url', models.TextField(max_length=5000)),
                ('icon_class', models.CharField(max_length=200)),
                ('field_type', models.CharField(default='text', max_length=200)),
                ('manager', models.CharField(default='social', max_length=200)),
                ('createat', models.DateTimeField(auto_now_add=True)),
                ('updateat', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
